# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab09e5839a56496e3abaf230ba87a0131543ffffafce2e65fb903cefb64aba1e8c3e1103084ab3fd8f1d082d9f6e0620e3d3ec8d742c155c277c121964ca7eec

test:
  secret_key_base: 6592a1bed82d9525c107d5e75ada34680ec2ff941786d82fa0827a2881cdf9e2697c9aeb6180391b9dab95fe0dec1577d6f7fb9240193ed9609f0b0655dc0991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
